// <auto-generated />
using System;
using BillObject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace QLHD.Migrations
{
    [DbContext(typeof(BillManagermentContext))]
    partial class BillManagermentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BillObject.Models.KhachHang", b =>
                {
                    b.Property<int?>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("MaKh"), 1L, 1);

                    b.Property<int?>("DinhMuc")
                        .HasColumnType("int");

                    b.Property<double?>("DonGia")
                        .HasColumnType("float");

                    b.Property<string>("HoTenKh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HoTenKH");

                    b.Property<int?>("LoaiKh")
                        .HasColumnType("int")
                        .HasColumnName("LoaiKH");

                    b.Property<string>("QuocTich")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<double?>("ThanhTien")
                        .HasColumnType("float");

                    b.HasKey("MaKh");

                    b.ToTable("KhachHang", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
